### ISSUE TITLE
Where is the config file

### ISSUE THREAD

**Issue by jrdwiz** [bolausson/SensorPush#2]
Where / how do I configure the config file?

**Comment by bolausson** [comment]
You can configure it or use the default as specified in the script:

https://github.com/bolausson/SensorPush/blob/9f3651dbfa16eb31b8ca22d86e512a6c22fff4be/sensorpush.py#L47

If you start sensorpush.py for the first time, it will create one for you containing placeholders.
Else look at the lines below the following:
https://github.com/bolausson/SensorPush/blob/9f3651dbfa16eb31b8ca22d86e512a6c22fff4be/sensorpush.py#L67
