### ISSUE TITLE
Unsupported Operand Types

### ISSUE THREAD

**Issue by StableFlux** [bolausson/SensorPush#4]
Hi Bjoern,

I am using your python program sensorpush.py as I only have influxdb V1.8.10 installed on my raspberry pi 4b+.
Here is the OS Verion:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
I'm having an issue where I am receiving the error:

`TypeError("unsupported operand type(s) for *: 'NoneType' and 'float'")`

Below is the console output when I run the code:

```
'Fetching API oauth authorization string'
'Fetching API oauth access token'
'Fetching the list of gateways'
'Fetching the list of bulk reports'
'Fetching the list of sensors'
'-------------------------------------------------------------------'
'Start: 2023-10-12T21:26:17+0000'
'Stop:  2023-10-13T21:26:17+0000'
'-------------------------------------------------------------------'
'Iterations required: 3'
'-------------------------------------------------------------------'
'Iteration 1/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
''
'##################Somthing went wrong################'
'~~~~~~~~~~~~Exception~~~~~~~~~~~~~'
TypeError("unsupported operand type(s) for *: 'NoneType' and 'float'")
'~~~~~~~~~~~~Request status code~~~~~~~~~~~~~'
200
'~~~~~~~~~~~~~~~~~~~~~~~~~'
```
If I let the program continue to run and try again, I noticed that I get a different exception:

```
'------------------------------------------------------'
'Retrying iteration 1/3'
'Try 1/3'
'sleeping for 60 seconds before next try'
'######################################################'
''
'Iteration 1/3'
''
'##################Somthing went wrong################'
'~~~~~~~~~~~~Exception~~~~~~~~~~~~~'
KeyError(0)
'~~~~~~~~~~~~Request status code~~~~~~~~~~~~~'
200
'~~~~~~~~~~~~~~~~~~~~~~~~~'
```

I was wondering if you would be able to offer any advice regarding a solution?

I hope this makes sense, and that I have provided enough information. I am very much an armature with coding and greatly appreciate any help that can be offered.

Thanks in advance...
SW

**EDIT:**

I though the error may be something to do with the conversions, like F to C, for example, but when I run:

`python sensorpush.py -n`

I get a different exception:

```
'##################Somthing went wrong################'
'~~~~~~~~~~~~Exception~~~~~~~~~~~~~'
InfluxDBClientError('400: {"error":"partial write: field type conflict: input field \\"temperature\\" on measurement \\"SensorPush\\" is type integer, already exists as type float dropped=2"}')
'~~~~~~~~~~~~Request status code~~~~~~~~~~~~~'
200
'~~~~~~~~~~~~~~~~~~~~~~~~~'
```

**Comment by bolausson** [comment]
Hello,

I think the underlaying problem is what you reported in the EDIT. The first time you run the script and it writes a value to InfluxDB, the type (int, float, ...) is defined. Meaning if a time series was initialized as type float (e.g. 1.123) and you try to write an int (e.g. 1), then influxDB will throw the error you provided in the EDIT.

So there seems to be an issue when you run the script for the first time and a value is not present. e.g. if the temperature is not present in a query, it wirtes 0.0 (a float) - which is stupid to be honest - it just should not write anything to InfluxDB.

So what you could do to track this down is:

1. Clear all your SensorPush InfluxDB time series
2. Run the script again (maybe it now gets all real values) and the probem is sorted

if the error comes again, then you have to find the value which was missing and was wrongly substitued by a wrong type.
If you want to debug it, add more "print()" statements to find our which values would be written as which type e.g.:
```
print("temperature")
print(C, type(C))
```

2. Run the script with --dryrun (it will not write anything to InfluxDB and rather print the dictionary that would have been written.)

Since I no longer have any InfluxDB 1.x instance I didn't do any further testing/debugging on the old version of the script.

So the prober way to sort this once and for all is:
If a measurement (e.g. pressure) is not provided from the SensorPush API, do not assume a value for this measurement, simply do not write the measurement to InfluxDB

E.g. if pressure was not provided, the key:value for pressure should be removed from the measurement dict
```
measurement.extend([
  {
	  'measurement': 'SensorPush',
	  'tags': {
		  'sensor_id': key,
		  'sensor_name': sensors[key]['name'],
	  },
	  'fields': {
		  'temperature': temperature,
		  'humidity': humidity,
		  'altitude': altitude,
		  'dewpoint': dewpoint,
		  'vpd': vpd,
		  'abs_humidity': abs_humidity
	  },
	  'time': observed
  }
])
```
instead of
```
measurement.extend([
  {
	  'measurement': 'SensorPush',
	  'tags': {
		  'sensor_id': key,
		  'sensor_name': sensors[key]['name'],
	  },
	  'fields': {
		  'temperature': temperature,
		  'humidity': humidity,
		  'pressure': pressure,
		  'altitude': altitude,
		  'dewpoint': dewpoint,
		  'vpd': vpd,
		  'abs_humidity': abs_humidity
	  },
	  'time': observed
  }
])
```
One could do that by

1. either dynamically create the initial dict so the missing value would not be in the dict in the first place
2. whenever a value is not defined by a value from the query, we asigne it a value of None of False and later, just before writing to InfluxDB, find all keys with a value of "None" or "False" and then pop it (e.g. dictionary.pop(''pressure"))

2. is a quick and dirty hack, 1. would need a bit more thinking - Since I personally have no more use for the old version, I will try to fix it for you with the second option - but I can only test it theoretically.

**Comment by bolausson** [comment]
Can you try the attached file (rename it to sensorpush.py)?
[sensorpush.txt](https://github.com/bolausson/SensorPush/files/12909901/sensorpush.txt)

Please clean your entire SensorPush measurements (or use a new name for the measurement) from InfluxDB before you report success or failure!

**CAVEAT**:
I changed the default config file from
`~/.sensorpush.conf`
to
`~/.sensorpush_legacy.conf`

**Comment by StableFlux** [comment]
Hi Bjoern,

Thanks for responding to this and your help.

After reading through your reply, here is an update:

1. I dropped the database then recreated it granting the user all privileges to the user. 
2. I checked the database through Grafana and confirmed that 0 measurements were found.
3. I ran the program using `python sensorpush.py` and got the exception `TypeError("unsupported operand type(s) for *: 'NoneType' and 'float'")` with Request Status Code: 200
4. I checked the database in Grafana again and found 1 measurement.
5. Exploring the data in Grafana I found **FROM: SensorPush_V**, **SELECT: field(rssi)** with 2 values &  **field(voltage)** with 2 values
6. I dropped and recreated the database and confirmed no measurements in Grafana.
7. I edited the code as follows:
```
measurement.extend([
  {
	  'measurement': 'SensorPush',
	  'tags': {
		  'sensor_id': key,
		  'sensor_name': sensors[key]['name'],
	  },
	  'fields': {
		  'temperature': temperature,
	  },
	  'time': observed
  }
])
```
For reference: I have 3 SensorPush HTP.xw sensors and a Gateway so all the readings should be available. However, for this use case I am only interested in the temperature which is why I edited the code this way.

8. I ran the program again with `python sensorpush.py` and got the exception `TypeError("unsupported operand type(s) for *: 'NoneType' and 'float'")` with Request Status Code: 200
9. I checked the database again with the same results but this time I only got 1 value for rssi & voltage.
10. I cleared the database again and this time ran `python sensorpush.py -x` and got the same exception: `TypeError("unsupported operand type(s) for *: 'NoneType' and 'float'")`
11. Checking the database this time confirmed no data was written as expected behaviour.
12. I edited the program again restoring to the original code for the `measurment.extended([])` section
13. I ran the code again with `python sensorpush.py -n` and this time it seemed to be working but then failed. The console output is below:
```
'Fetching API oauth authorization string'
'Fetching API oauth access token'
'Fetching the list of gateways'
'Fetching the list of bulk reports'
'Fetching the list of sensors'
'-------------------------------------------------------------------'
'Start: 2023-10-14T14:42:43+0000'
'Stop:  2023-10-15T14:42:43+0000'
'-------------------------------------------------------------------'
'Iterations required: 3'
'-------------------------------------------------------------------'
'Iteration 1/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 2/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 3/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
''
'##################Somthing went wrong################'
'~~~~~~~~~~~~Exception~~~~~~~~~~~~~'
InfluxDBClientError('400: {"error":"partial write: field type conflict: input field \\"temperature\\" on measurement \\"SensorPush\\" is type integer, already exists as type float dropped=2"}')
'~~~~~~~~~~~~Request status code~~~~~~~~~~~~~'
200
'~~~~~~~~~~~~~~~~~~~~~~~~~'
```
There is now data in the database, but it looks pretty messed up:
<img width="1113" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/95f25540-63d9-4e9c-82e4-d95dae46d286">
This is the 2 day view

<img width="1114" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/dc808c7d-92d5-4439-aa24-57a2dd76cd96">
This is the 24 Hour View

<img width="1109" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/03226434-e8bf-4a21-a719-d83234125de9">
This is the 60 Minutes View

14. Lastly dropped and recreated the databases again and then ran `python sensorpush -nq 10` and this seemed to work:
```
'Fetching API oauth authorization string'
'Fetching API oauth access token'
'Fetching the list of gateways'
'Fetching the list of bulk reports'
'Fetching the list of sensors'
'-------------------------------------------------------------------'
'Start: 2023-10-14T15:05:28+0000'
'Stop:  2023-10-15T15:05:28+0000'
'-------------------------------------------------------------------'
'Iterations required: 3'
'-------------------------------------------------------------------'
'Iteration 1/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 2/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 3/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
```
Reviewing the data in Grafana it looks like this:
<img width="1108" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/28da5220-6869-44db-9ed5-0941f203e8cf">
24 Hours

<img width="1120" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/b0633658-8b51-472b-919a-7a61158de36d">
60 Minutes

Reviewing the data available in Grafana we can see that all the expected data types are available: 
<img width="401" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/ffcb51b9-48f8-4cb3-bf40-fd09254bd57e">

However I don't seem to have different data for each of the 3 sensors. For example it looks like the temperature data for all 3 of the sensors has been combined into a tingle 'temperature' data source.

Lastly, I would like to look into trying one of your early suggestions where you say I should implement more `print()` statements, 
 but I'm not sure exactly where to put them. Sorry... As I mentioned I'm not a coder but only try to learn in my free time.

Thanks so much for your help, I have learned so much from working through your code - thank you.

SW

**Comment by StableFlux** [comment]
> Can you try the attached file (rename it to sensorpush.py)? [sensorpush.txt](https://github.com/bolausson/SensorPush/files/12909901/sensorpush.txt)
> 
> Please clean your entire SensorPush measurements (or use a new name for the measurement) from InfluxDB before you report success or failure!
> 
> **CAVEAT**: I changed the default config file from `~/.sensorpush.conf` to `~/.sensorpush_legacy.conf`

Thanks so much for this file, I can confirm that running `python sensorpush.py` completes with no exceptions:

```
'Fetching API oauth authorization string'
'Fetching API oauth access token'
'Fetching the list of gateways'
'Fetching the list of bulk reports'
'Fetching the list of sensors'
'-------------------------------------------------------------------'
'Start: 2023-10-14T15:24:14+0000'
'Stop:  2023-10-15T15:24:14+0000'
'-------------------------------------------------------------------'
'Iterations required: 3'
'-------------------------------------------------------------------'
'Iteration 1/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 2/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
'Iteration 3/3'
'Request truncated: False'
'Number of samples fetched: 30'
'Number of sensors queried: 3'
'------------------------------------------------------'
'sleeping for 60 seconds'
'------------------------------------------------------'
```

The thing now is that it still seems to only collect data that is about 30 minutes old and it also combines all the readings for a type so instead of readings for **Sensor 1: Temp**, **Sensor 2: Temp**, **Sensor 3: Temp** we just get **Temp**

<img width="1244" alt="image" src="https://github.com/bolausson/SensorPush/assets/10962965/ccb2b2eb-0d0c-4118-b707-7d2f29338c38">

Is this expected behaviour and as designed?
I thought reading through the code that each sensor's unique id was used to separate the readings - or am I wrong?

Thanks again for your time and help!!

SW

**Comment by bolausson** [comment]
Just one note:

I never tried the old cold with the newer sensors - I have them as well, but never tried it with the legacy code.
In sensorpush2.py I am creating the "fields" dynamically from what the sensor reports, in the legacy code, the values gathered from the newer sensors are hard coded as you can see.

You can try to take sensorpush2.py and convert it back to InfluxDB 1.x - you could use sensorpush.py as en exmaple and steal the "old" way of writing to InfluxDB 1.x from there.

Regarding your plotting problem - did you try to import the [SensorPush-GrafanaDashboard.json](https://github.com/bolausson/SensorPush/blob/master/SensorPush-GrafanaDashboard.json) which I provided?

Your query should look something like that:
![image](https://github.com/bolausson/SensorPush/assets/10600678/650426b0-bb8a-49ce-9002-b378bc3ec4c4)

![Screenshot 2023-10-15 174920](https://github.com/bolausson/SensorPush/assets/10600678/975791cf-bc2e-4019-bd09-026f17969136)

For the granularity... no idea whats going on. Did you check on https://dashboard.sensorpush.com/ how it looks there?

If you want to query older values than one day, checn sensorpush.py --help for the options

**Comment by StableFlux** [comment]
Hi Bjoern,

With your help and the new file that you sent through I managed to get it working fully.

Thanks very much for all your help - this is an awesome program and very helpful for me.

I really appreciate your time and help.

SW

**Comment by bolausson** [comment]
Thanks for the feedback - I pushed the changes to the repo.

Have fun :)
