### ISSUE TITLE
saving in inflexDB and on excel

### ISSUE THREAD

**Issue by houdault** [bolausson/SensorPush#5]

**Comment by bolausson** [comment]
Sorry, but I can't help you on that one.

1. The unmodified code works perfectly fine for me with two gateways and 16 sensors (across all versions and iterations of the sensor hardware)
2. Writing data to an excel file was never the intention of this tool and is not part of my original code!
4. I will not debug your (modified) code for you!
5. What you pasted is unreadable and essentially an insult to everyone who is willing to help.
If you expect help, you should put in a tad more effort to format your query in such a way that it is easy to read and understand (not everyone speaks Spanish) for others!

Please reproduce your problem with my original, unmodified code!
If there is a problem, I am willing to investigate it.

Attaching a screenshot just for reference:
![screenshot-github_com-2024_10_29-19_26_48](https://github.com/user-attachments/assets/7064582e-5838-433f-8ab4-0e926676d8e9)

**Comment by houdault** [comment]
ok I don´t think that was to react like this but it´s ok.

**Comment by houdault** [comment]
like you said how you will help me if your code didnt save in excel.
thanks

**Comment by bolausson** [comment]
Sorry, but I don't understand what you are writing.

Can you reproduce the probme "just save 10 datas from one sensor" with my unmodified code sensorpush2.py?

**Comment by houdault** [comment]
no, because your code don´t have this option

**Comment by houdault** [comment]
you don t want help me , it´s ok.
I'm sorry, I didn't notice either the format change or the language; I copied it directly from Spyder...
